version: "3.7"

services:
  nest-app:
    build: server
    container_name: nest-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3000/api/healthcheck || exit 1"]
      interval: 50s
      timeout: 30s
      retries: 5
    depends_on:
      - nest-elasticsearch
    command: "npm run start:dev"
    volumes:
      - ./server/src:/app/server/src/
    ports:
      - 3000:3000
  nest-elasticsearch:
    container_name: nest-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cat/health?h=st || exit 1"]
      interval: 50s
      timeout: 30s
      retries: 5
    environment:
      - cluster.name=movies-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9300:9300
      - 9200:9200
  nest-vue:
    build:
      target: 'develop-stage'
      context: client
    container_name: nest-vue
    volumes:
      - ./client:/app/client
    ports:
      - 8080:8080
    command: /bin/sh -c "npm run serve"
